### PR TITLE
chore: Delete unnecesary mutable variable when create COMMENT_TEMPLATES static

### PR DESCRIPTION
**Pull request by thenatx**
This pull request change the way in the COMMENT_TEMPLATES is created at ``src/bot/events/read_github_links.rs``

the old way was create a temporary mutable var with a empty hashmap and the use ``insert`` for add the field for each language
```rs
    static ref COMMENT_TEMPLATES: HashMap<&'static str, &'static str> = {
        let mut m = HashMap::new();
        m.insert("c", "// {}");
        m.insert("cpp", "// {}");
        // other languages...
        m
    };
```

The var ``m`` is unnecessary so with the changes the hashmap is created using an array of tuples instead 
```rs
static ref COMMENT_TEMPLATES: HashMap<&'static str, &'static str> = HashMap::from([
    ("c", "// {}"),
    ("cpp", "// {}"),
    // other languages...
]);
```

### CODE REVIEW

**Comment by stifskere** [comment]
I haven't checked, but iirc that was the only use of `lazy_static`, thus it could be removed from the dependencies.

**Comment by thenatx** [comment]
I think that is ready

**Comment by stifskere** [comment]
LGTM

**Review by SergioRibera — APPROVED** [review]
LGTM! Thanks for contributing 🦀

**Pull request merged**
